#!/bin/bash

mkdir -p "${HOME}/.config/karabiner/assets/complex_modifications/"
cp ./capslock.json "${HOME}/.config/karabiner/assets/complex_modifications/capslock.json"
echo "${HOME}/.config/karabiner/assets/complex_modifications/capslock.json" Done