#!/bin/bash

mkdir -p "${HOME}/.config/karabiner/assets/complex_modifications/"
cp ./caps_lock.json "${HOME}/.config/karabiner/assets/complex_modifications/caps_lock.json"
echo "${HOME}/.config/karabiner/assets/complex_modifications/caps_lock.json" Done
