---
################################################################
#                       Hyper Functional                       #
################################################################

rules:
  - description: Hyper Functional
    manipulators:


      #==========================================================#
      # F1 - F3 --> Desktop (require preference->shortcut setup) #
      #==========================================================#
      - description: 'command + F1 = desktop 1'
        type: basic
        from: { key_code: f1, modifiers: { mandatory: [ left_command,  right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '1' , modifiers: [ left_control ] } ]

      - description: 'command + F2 = desktop 2'
        type: basic
        from: { key_code: f2, modifiers: { mandatory: [ left_command,  right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '2' , modifiers: [ left_control ] } ]

      - description: 'command + F3 = desktop 3'
        type: basic
        from: { key_code: f3, modifiers: { mandatory: [ left_command,  right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '3' , modifiers: [ left_control ] } ]


      #==========================================================#
      # F1 - F12 --> Real Function                               #
      #==========================================================#
      - description: 'F1 = display_brightness_decrement'
        type: basic
        from: { key_code: f1, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: display_brightness_decrement } ]

      - description: 'F2 = display_brightness_increment'
        type: basic
        from: { key_code: f2, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: display_brightness_increment } ]

      - description: 'F3 = Expose All'
        type: basic
        from: { key_code: f3, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: up_arrow , modifiers: [ left_control ] } ]

      - description: 'F4 = LaunchPad'
        type: basic
        from: { key_code: f4, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { shell_command: open -a 'Launchpad' } ]

      - description: 'F5 = illumination_decrement'
        type: basic
        from: { key_code: f5, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: illumination_decrement } ]

      - description: 'F6 = illumination_increment'
        type: basic
        from: { key_code: f6, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: illumination_increment } ]

      - description: 'F7 = rewind'
        type: basic
        from: { key_code: f7, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: rewind } ]

      - description: 'F8 = play_or_pause'
        type: basic
        from: { key_code: f8, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: play_or_pause } ]

      - description: 'F9 = fastforward'
        type: basic
        from: { key_code: f9, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: fastforward } ]

      - description: 'F10 = mute'
        type: basic
        from: { key_code: f10, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: mute } ]

      - description: 'F11 = volume_decrement'
        type: basic
        from: { key_code: f11, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: volume_decrement } ]

      - description: 'F12 = volume_increment'
        type: basic
        from: { key_code: f12, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: volume_increment } ]

      #==========================================================#
      # ~ --> area selection snapshot                            #
      #==========================================================#
      - description: 'command + ~ = area snap to desktop file'
        type: basic
        from: { key_code: grave_accent_and_tilde, modifiers: { mandatory: [ left_command,  right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '4' , modifiers: [ left_shift,left_command ] } ]

      - description: '~ = area snap to clipboard'
        type: basic
        from: { key_code: grave_accent_and_tilde, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '4' , modifiers: [ left_shift,left_command,left_control ] } ]

      #==========================================================#
      # Screenshot (F13) --> Screenshot                          #
      #==========================================================#
      - description: 'command + ~ = area snap to desktop file'
        type: basic
        from: { key_code: f13, modifiers: { mandatory: [ left_command,  right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '3' , modifiers: [ left_shift,left_command ] } ]

      - description: '~ = area snap to clipboard'
        type: basic
        from: { key_code: f13, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '3' , modifiers: [ left_shift,left_command,left_control ] } ]

      #==========================================================#
      # ScrollLock (F14) --> Advanced Screenshot                 #
      #==========================================================#
      - description: 'command + ScrollLock = area snap to desktop file'
        type: basic
        from: { key_code: f14, modifiers: { mandatory: [ left_command,  right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '6' , modifiers: [ left_shift,left_command ] } ]

      - description: 'ScrollLock = screen video capture'
        type: basic
        from: { key_code: f14, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: '5' , modifiers: [ left_shift,left_command ] } ]

      #==========================================================#
      # Pause (F15) --> play_or_pause                            #
      #==========================================================#
      - description: 'ScrollLock = screen video capture'
        type: basic
        from: { key_code: f15, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: play_or_pause } ]

      #==========================================================#
      # Ins/Del/Home/End/PgUp/PgDn -> Fine-Grained Control       #
      #==========================================================#
      - description: 'insert = display_brightness_increment'
        type: basic
        from: { key_code: insert, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: display_brightness_increment, modifiers: [ left_shift, left_option ] } ]

      - description: 'delete_forward = display_brightness_decrement'
        type: basic
        from: { key_code: delete_forward, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: display_brightness_decrement, modifiers: [ left_shift, left_option ] } ]

      - description: 'home = illumination_increment'
        type: basic
        from: { key_code: home, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: illumination_increment, modifiers: [ left_shift, left_option ] } ]

      - description: 'end = illumination_decrement'
        type: basic
        from: { key_code: end, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: illumination_decrement, modifiers: [ left_shift, left_option ] } ]

      - description: 'page_up = volume_increment'
        type: basic
        from: { key_code: page_up, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: volume_increment, modifiers: [ left_shift, left_option ] } ]

      - description: 'page_down = volume_decrement'
        type: basic
        from: { key_code: page_down, modifiers: { mandatory: [ right_command,right_control,right_shift,right_option ] } }
        to: [ { key_code: volume_decrement, modifiers: [ left_shift, left_option ] } ]

...
